### ISSUE TITLE
Wrong detection of methods class

### ISSUE THREAD

**Issue by Dgame** [phpfmt/php.oracle#4]
```php
<?php

class Bar {
    public function fooquatz() {

    }
}

class Foo {
    public function foobar() {
        
    }
}
```

It seems that the Parser detects erroneously that `fooquatz` and ` foobar` belongs to Foo.

**Comment by dericofilho** [comment]
I tested with HEAD.

```
$ php oracle.src.php autocomplete
term,match,class,type
"\Bar",Bar,"\Bar",class
"\Foo",Foo,"\Foo",class
"\Bar",Bar,"\Bar",class
"\Foo",Foo,"\Foo",class
fooquatz(),fooquatz(),"\Bar",method
foobar(),foobar(),"\Foo",method
```

**Comment by Dgame** [comment]
I've just printed into the console and it looked wrong. But indeed the SQL result looks valid. Sorry. I thought that would be the problem of the autocompletion. :D

**Comment by dericofilho** [comment]
Likely it is a plugin issue, not an engine issue. Thanks for reporting.
